"""empty message

Revision ID: 26428efbe256
Revises: 18063a4eae98
Create Date: 2018-03-01 13:18:39.035432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26428efbe256'
down_revision = '18063a4eae98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('cId', sa.Integer(), nullable=False),
    sa.Column('uId', sa.Integer(), nullable=True),
    sa.Column('aId', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aId'], ['article.aId'], ),
    sa.ForeignKeyConstraint(['uId'], ['user.uId'], ),
    sa.PrimaryKeyConstraint('cId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
