"""empty message

Revision ID: edf9e6d0b501
Revises: c0f39079eb26
Create Date: 2018-01-21 10:20:12.434576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf9e6d0b501'
down_revision = 'c0f39079eb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('time', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'time')
    # ### end Alembic commands ###
